### ISSUE TITLE
Reprendre le footer suivant la maquette

### ISSUE THREAD

**Issue by victorjourne** [datalab-mi/ridoc#124]
[maquette](https://xd.adobe.com/view/26371e98-be07-448a-bd4f-03b1b3160bbe-7364/screen/ea5108f4-cdf4-4fa4-a1ab-5f96b96d09ec/)
- [ ]  Ne pas prendre en compte la section *nous suivre*
- [ ] Paramétrer les liens dans la [config] (https://github.com/datalab-mi/moteur-de-recherche/blob/dev/backend/tests/iga/static/env.json) ou bien dans un nouveau fichier spécial footer si jugé nécessaire

**Comment by aurelienmart** [comment]
Liens du footer description et exemples:

- **Plan du site**: explication des différents onglets: https://www.legifrance.gouv.fr/contenu/pied-de-page/plan-du-site
- **Mentions légales**: responsabilité juridique, gestionnaire hebergement ... : https://www.legifrance.gouv.fr/contenu/pied-de-page/mentions-legales , https://code.travail.gouv.fr/mentions-legales
- **Accessibilité** information sur normes et audits: https://code.travail.gouv.fr/accessibilite
- **Données personnelles et sécurité,** politique de confidentialité: https://code.travail.gouv.fr/politique-confidentialite
- **Engagement et qualité**, à propos (description du but du site) + questionnaire qualité: https://code.travail.gouv.fr/a-propos
