### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by mpw-user** [datalab-mi/ridoc#36]
https://flask-httpauth.readthedocs.io/en/latest/

https://www.digitalocean.com/community/tutorials/how-to-add-authentication-to-your-app-with-flask-login-fr
Comment ajouter une authentification à votre application avec Flask-Login | DigitalOcean
Permettre aux utilisateurs de se connecter à votre application est l'une des fonctionnalités les plus courantes que vous ajouterez à votre application web. Cet article explique comment ajouter une ...

**Comment by victorjourne** [comment]
Sinon avec des tokens: https://realpython.com/token-based-authentication-with-flask/

Ou encore https://blog.tecladocode.com/simple-jwt-authentication-with-flask-jwt/

**Comment by mpw-user** [comment]
Introduction à jwt:
https://www.vaadata.com/blog/fr/jetons-jwt-et-securite-principes-et-cas-dutilisation/

Flask-jwt (code source et requêtes):
https://pythonhosted.org/Flask-JWT/#quickstart

**Comment by mpw-user** [comment]
Réponses des requests:

**/auth**
HTTP/1.1 200 OK
Server: nginx/1.19.5
Date: Fri, 04 Dec 2020 15:26:25 GMT
Content-Type: application/json
Content-Length: 193
Connection: keep-alive

{
  "access_token": "_le_token_"
}

**/auth avec mauvais credentials**
HTTP/1.1 401 UNAUTHORIZED
Server: nginx/1.19.5
Date: Fri, 04 Dec 2020 15:36:50 GMT
Content-Type: application/json
Content-Length: 93
Connection: keep-alive

{
  "description": "Invalid credentials", 
  "error": "Bad Request", 
  "status_code": 401
}

**Requete sans token**
HTTP/1.1 401 UNAUTHORIZED
Server: nginx/1.19.5
Date: Fri, 04 Dec 2020 15:32:03 GMT
Content-Type: application/json
Content-Length: 125
Connection: keep-alive
WWW-Authenticate: JWT realm="Login Required"

{
  "description": "Request does not contain an access token", 
  "error": "Authorization Required", 
  "status_code": 401
}

**Requete avec mauvais token**
HTTP/1.1 401 UNAUTHORIZED
Server: nginx/1.19.5
Date: Fri, 04 Dec 2020 15:38:59 GMT
Content-Type: application/json
Content-Length: 97
Connection: keep-alive

{
  "description": "Signature has expired", 
  "error": "Invalid token", 
  "status_code": 401
}

_description peut aussi contenir "Not enough segments", "Signature verification failed"_


**Requete avec bon token**
HTTP/1.1 201 CREATED
Server: nginx/1.19.5
Date: Fri, 04 Dec 2020 15:43:14 GMT
Content-Type: application/json
Content-Length: 21
Connection: keep-alive

{
  "sucess": true
}

**Comment by mpw-user** [comment]
Loggin
curl -X POST -H "Content-Type: application/json" \
    -d '{"username": "user1", "password": "abcxyz"}' \
    http://localhost:81/api/auth


Requete sur la route admin/threshold:
curl -X PUT -H "Content-Type: application/json" \
    -H "Authorization: JWT le_token_récuperé" \
    -d '{"d_threshold": 5, "r_threshold": 5}' \
    http://localhost:81/api/admin/threshold

**Comment by mpw-user** [comment]
Liens utils:


JWT token storage discussion: https://dev.to/gkoniaris/how-to-securely-store-jwt-tokens-51cf
JWT token storage in cache (extended version) :
https://flask-jwt-extended.readthedocs.io/en/stable/tokens_in_cookies/


JWT credential storage:
https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/#a-minimal-application


Nginx auth: where to put .htpasswd
https://askubuntu.com/questions/489825/where-should-i-place-the-htpasswd-file-phpmyadmin#:~:text=htpasswd%20file%20in%20%2Fvar%2Fwww,it%20in%20%2Fetc%2Fphpmyadmin%20.
Commentaire: passlib comme librairie hashage de pasword (// htpasw)?
