### ISSUE TITLE
Apparence de baseItem

### ISSUE THREAD

**Issue by victorjourne** [datalab-mi/ridoc#91]
BaseItem est le composant de base de NewItem et Resultitem
- [x] Le paramètre backgroundColor de preferences.theme.search.results doit gérer la couleur de fond de baseItem
- [x] Est-ce possible de rajouter des clefs à preferences.theme.search.results pour modifier le css de BaseItem?
- [ ] Peut on mettre dans le css de BaseItem les styles des boutons?

**Comment by yerb-wavestone** [comment]
style des boutons : je propose un composant dédié qui intègre le style, qu'on peut encore surcharger un peu.

sur l'écran de recherche il y a le bouton de recherche "responsive" et les boutons de résultats, le composant permettrait d'harmoniser
